FROM python:3.6.2
ADD ./ScrapyNews /docker_api
WORKDIR /docker_api
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN mkdir static
RUN mkdir ./static/css
RUN mkdir ./static/js
RUN mkdir ./static/images
RUN mkdir ./static/fonts
